# =============================================
# DataSource — PostgreSQL
# =============================================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/siw_palestra_coppia}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#aggiunta su JPA Hibernate per l'esecuzione di data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# =============================================
# Thymeleaf
# =============================================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# =============================================
# App
# =============================================
spring.application.name=siw-palestra
server.port=${PORT:8080}
